export const EXCHANGES = "EXCHANGES";
export const SET_TICKER = "SET_TICKER";
export const GET_TICKER_FETCH = "GET_TICKER_FETCH";
export const GET_TICKER_SUCCESS = "GET_TICKER_SUCCESS";
export const GET_TICKER_ERROR = "GET_TICKER_ERROR";
