export const SELECTED_EXCHANGED_ID = "SELECTED_EXCHANGED_ID";
export const EXCHANGES = "EXCHANGES";
export const SET_TICKER = "SET_TICKER";
export const GET_TICKER_FETCH = "GET_TICKER_FETCH";
export const GET_TICKER_SUCCESS = "GET_TICKER_SUCCESS";
